[workspace]
resolver = "2"
members = ["simulator", "solvers", "game_data"]

[package]
name = "raphael-xiv"
version = "0.12.2"
edition = "2021"

[dependencies]
simulator = { path = "simulator" }
solvers = { path = "solvers" }
game-data = { path = "game_data" }

egui = "0.27.2"

eframe = { version = "0.27.2", features = ["persistence"] }
egui_extras = { version = "0.27.2", features = ["all_loaders"] }
image = { version = "0.24", features = ["jpeg", "png"] }
wasm-bindgen-futures = "0.4"
gloo-worker = { version = "0.5.0", features = ["futures"] }
serde = { version = "1.0.203", features = ["derive"] }
log = "0.4"
web-time = "1.1.0"
console_error_panic_hook = "0.1.7"

[[bin]]
name = "webworker"
path = "src/webworker.rs"

[profile.release]
lto = "fat"
